name: Cleanup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  cleanup:
    name: System Cleanup
    runs-on: self-hosted
    
    steps:
    - name: Clean old deployments
      run: |
        echo "🧹 Cleaning old frontend backups..."
        sudo find /var/www/aladin-frontend/backup-* -type d -mtime +7 -exec rm -rf {} \; 2>/dev/null || true
        echo "✅ Old deployments cleaned"

    - name: Clean nginx logs
      run: |
        sudo truncate -s 0 /var/log/nginx/access.log 2>/dev/null || true
        sudo truncate -s 0 /var/log/nginx/error.log 2>/dev/null || true
        echo "✅ Nginx logs cleared"

    - name: Clean npm cache
      run: |
        npm cache clean --force 2>/dev/null || true
        echo "✅ npm cache cleaned"

    - name: Show disk usage
      run: |
        echo "📊 Disk usage:"
        df -h /var/www/ || true

