name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality & Security
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check outdated packages
        run: npm outdated
        continue-on-error: true

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Check file sizes
        run: |
          echo "Checking bundle sizes..."
          npm run build
          du -sh dist/
          find dist/assets -name "*.js" -exec du -h {} \;
        shell: bash

      - name: Dependency tree
        run: npm list --depth=0
        continue-on-error: true

      - name: Summary
        run: |
          echo "✅ Code quality checks completed!"
          echo "📦 Build size: $(du -sh dist/ | cut -f1)"
          echo "🔒 Security audit: Check logs above"
        shell: bash

